DROP TABLE IF EXISTS film_genre CASCADE;
DROP TABLE IF EXISTS ratings CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS films CASCADE;
DROP TABLE IF EXISTS genre CASCADE;
DROP TABLE IF EXISTS likes CASCADE;
DROP TABLE IF EXISTS friends CASCADE;

CREATE TABLE IF NOT EXISTS genres(
    genre_id integer PRIMARY KEY,
    name varchar
);

CREATE TABLE IF NOT EXISTS ratings(
    mpa_id integer PRIMARY KEY,
    name varchar
);

CREATE TABLE IF NOT EXISTS films(
    film_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar,
    description varchar(200),
    mpa_id integer REFERENCES ratings (mpa_id),
    release_date date,
    duration integer
);

CREATE TABLE IF NOT EXISTS users(
    user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar,
    login varchar UNIQUE NOT NULL,
    email varchar UNIQUE NOT NULL,
    birthday date
);

CREATE TABLE IF NOT EXISTS film_genre(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id integer REFERENCES films (film_id),
    genre_id integer REFERENCES genres (genre_id)
);

CREATE TABLE IF NOT EXISTS likes(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id integer REFERENCES films (film_id),
    user_id integer REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS friends(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer REFERENCES users (user_id),
    friend_id integer REFERENCES users (user_id)
);